packages:
  - apps/*
  - packages/*
catalog:
  "@auth/core": 0.37.4
  "@babel/generator": 7.26.2
  "@clack/prompts": 0.8.2
  "@dnd-kit/core": ^6.2.0
  "@egoist/tailwindcss-icons": 1.8.1
  "@egoist/tipc": 0.3.2
  "@electron-forge/cli": 7.6.0
  "@electron-forge/maker-dmg": 7.6.0
  "@electron-forge/maker-squirrel": 7.6.0
  "@electron-forge/maker-zip": 7.6.0
  "@electron-forge/plugin-fuses": 7.6.0
  "@electron-forge/publisher-github": 7.6.0
  "@electron-toolkit/preload": ^3.0.1
  "@electron-toolkit/tsconfig": ^1.0.1
  "@electron-toolkit/utils": ^3.0.0
  "@eneris/push-receiver": 4.3.0
  "@essentials/request-timeout": 1.3.0
  "@fastify/middie": 9.0.2
  "@fastify/request-context": 6.0.1
  "@fontsource/sn-pro": 5.1.0
  "@headlessui/react": 2.2.0
  "@hono/node-server": 1.13.7
  "@hookform/resolvers": 3.9.1
  "@iconify-json/logos": 1.2.3
  "@iconify-json/mingcute": 1.2.1
  "@iconify-json/simple-icons": ^1.2.13
  "@iconify/tools": 4.0.7
  "@lottiefiles/dotlottie-react": 0.10.1
  "@microflash/remark-callout-directives": 4.3.2
  "@mozilla/readability": ^0.5.0
  "@openpanel/web": 1.0.1
  "@pengx17/electron-forge-maker-appimage": 1.2.1
  "@radix-ui/react-avatar": 1.1.1
  "@radix-ui/react-checkbox": 1.1.2
  "@radix-ui/react-context-menu": 2.2.2
  "@radix-ui/react-dialog": 1.1.2
  "@radix-ui/react-dropdown-menu": 2.1.2
  "@radix-ui/react-hover-card": 1.1.2
  "@radix-ui/react-label": 2.1.0
  "@radix-ui/react-navigation-menu": 1.2.1
  "@radix-ui/react-popover": 1.1.2
  "@radix-ui/react-radio-group": 1.2.1
  "@radix-ui/react-scroll-area": 1.2.1
  "@radix-ui/react-select": 2.1.2
  "@radix-ui/react-slider": ^1.2.1
  "@radix-ui/react-slot": 1.1.0
  "@radix-ui/react-switch": 1.1.1
  "@radix-ui/react-tabs": 1.1.1
  "@radix-ui/react-toast": 1.2.2
  "@radix-ui/react-tooltip": 1.1.4
  "@react-hook/window-size": 3.1.1
  "@resvg/resvg-js": 2.6.2
  "@sentry/electron": 5.7.0
  "@sentry/react": 8.41.0
  "@sentry/vite-plugin": 2.22.6
  "@shikijs/transformers": 1.24.0
  "@t3-oss/env-core": ^0.11.1
  "@tailwindcss/container-queries": 0.1.1
  "@tailwindcss/typography": 0.5.15
  "@tanstack/query-sync-storage-persister": 5.62.0
  "@tanstack/react-query": 5.62.0
  "@tanstack/react-query-devtools": 5.62.0
  "@tanstack/react-query-persist-client": 5.62.0
  "@tanstack/react-virtual": 3.10.9
  "@types/html-minifier-terser": 7.0.2
  "@types/js-yaml": 4.0.9
  "@types/katex": 0.16.7
  "@types/node": ^22.10.1
  "@types/react": ^18.3.12
  "@types/react-dom": ^18.3.1
  "@use-gesture/react": 10.3.1
  "@vercel/node": 3.2.27
  "@vite-pwa/assets-generator": ^0.2.6
  "@vitejs/plugin-legacy": 6.0.0
  "@vitejs/plugin-react": ^4.3.4
  "@welldone-software/why-did-you-render": 8.0.3
  "@yornaath/batshit": 0.10.1
  async-es: ^3.2.6
  autoprefixer: 10.4.20
  better-auth: 1.0.7
  blurhash: 2.0.5
  builder-util-runtime: 9.2.10
  camelcase-keys: 9.1.3
  chokidar: 4.0.1
  class-variance-authority: 0.7.1
  click-to-react-component: 1.1.2
  clsx: 2.1.1
  cmdk: 1.0.4
  cross-env: 7.0.3
  cssnano: 7.0.6
  daisyui: 4.12.14
  dayjs: 1.11.13
  dexie: 4.0.10
  dexie-export-import: ^4.1.4
  dnum: ^2.14.0
  dotenv: 16.4.5
  dotenv-flow: 4.1.0
  drizzle-orm: 0.36.4
  electron: 33.2.0
  electron-context-menu: 4.0.4
  electron-devtools-installer: 3.2.0
  electron-log: 5.2.3
  electron-packager-languages: 0.5.0
  electron-squirrel-startup: 1.0.1
  electron-updater: ^6.3.9
  electron-vite: ^2.3.0
  embla-carousel-react: 8.5.1
  embla-carousel-wheel-gestures: 8.0.1
  es-toolkit: 1.29.0
  eslint: ^9.16.0
  eslint-config-hyoban: ^3.1.14
  fake-indexeddb: 6.0.0
  fast-folder-size: 2.3.0
  fastify: 5.1.0
  firebase: 11.0.2
  font-list: 1.5.1
  foxact: 0.2.42
  framer-motion: 11.12.0
  franc-min: 6.2.0
  fuse.js: 7.0.0
  glob: 11.0.0
  happy-dom: 15.11.7
  hast-util-to-jsx-runtime: 2.3.2
  hast-util-to-mdast: ^10.1.1
  hast-util-to-text: 4.0.2
  hono: 4.6.12
  html-minifier-terser: 7.2.0
  i18next: ^24.0.2
  i18next-browser-languagedetector: 8.0.0
  idb-keyval: 6.2.1
  immer: 10.1.1
  jotai: 2.10.3
  js-yaml: 4.1.0
  katex: 0.16.11
  kose-font: 1.0.0
  lethargy: 1.0.9
  lightningcss: 1.28.2
  linkedom: ^0.18.5
  lint-staged: 15.2.10
  lowdb: 7.0.1
  masonic: 4.0.1
  mdast-util-gfm-table: ^2.0.0
  mdast-util-to-markdown: ^2.1.2
  msedge-tts: 1.3.4
  nanoid: 5.0.9
  nbump: 2.0.7
  node-machine-id: 1.1.12
  ofetch: 1.4.1
  path-to-regexp: 8.2.0
  plain-shiki: 0.0.12
  postcss: 8.4.49
  postcss-js: 4.0.1
  prettier: 3.4.1
  raw-body: 3.0.0
  rc-modal-sheet: 0.3.2
  re-resizable: 6.10.1
  react: ^18.3.1
  react-blurhash: ^0.3.0
  react-dom: ^18.3.1
  react-error-boundary: 4.1.2
  react-fast-marquee: 1.6.5
  react-hook-form: 7.53.2
  react-hotkeys-hook: 4.6.1
  react-i18next: ^15.1.3
  react-intersection-observer: 9.13.1
  react-ios-pwa-prompt: ^2.0.6
  react-photo-view: 1.2.6
  react-resizable-layout: npm:@innei/react-resizable-layout@0.7.3-fork.1
  react-router: 7.0.1
  react-scan: 0.0.35
  react-selecto: ^1.26.3
  react-shadow: 20.5.0
  react-zoom-pan-pinch: ^3.6.1
  rehype-infer-description-meta: 2.0.0
  rehype-parse: 9.0.1
  rehype-sanitize: 6.0.0
  rehype-stringify: 10.0.1
  remark-directive: 3.0.0
  remark-gfm: 4.0.0
  remark-gh-alerts: 0.0.3
  remark-parse: 11.0.0
  remark-rehype: 11.1.1
  rimraf: 6.0.1
  satori: 0.12.0
  semver: 7.6.3
  shiki: 1.24.0
  shx: ^0.3.4
  simple-git-hooks: 2.11.1
  sonner: 1.7.0
  tailwind-merge: 2.5.5
  tailwindcss: 3.4.15
  tailwindcss-animate: 1.0.7
  tailwindcss-motion: 0.4.3-beta
  tailwindcss-safe-area: 0.6.0
  tar: 7.4.3
  tldts: 6.1.65
  tsup: 8.3.5
  tsx: 4.19.2
  turbo: 2.3.3
  typescript: 5.7.2
  unified: 11.0.5
  uniqolor: 1.1.1
  unist-util-visit-parents: ^6.0.1
  unplugin-ast: ^0.12.0
  use-context-selector: 2.0.0
  use-pull-to-refresh: 2.4.1
  use-sync-external-store: 1.2.2
  usehooks-ts: 3.1.0
  vaul: 1.1.1
  vfile: 6.0.3
  vite: 6.0.2
  vite-bundle-analyzer: 0.15.2
  vite-plugin-mkcert: 1.17.6
  vite-plugin-pwa: 0.21.1
  vite-tsconfig-paths: 5.1.3
  vitest: 2.1.6
  vscode-languagedetection: npm:@vscode/vscode-languagedetection@^1.0.22
  web-push: 3.6.7
  xss: 1.0.15
  zod: 3.23.8
  zustand: 5.0.1
