name: nightly

on:
  push:

env:
  VITE_WEB_URL: ${{ vars.VITE_WEB_URL }}
  VITE_API_URL: ${{ vars.VITE_API_URL }}
  VITE_IMGPROXY_URL: ${{ vars.VITE_IMGPROXY_URL }}

jobs:
  build:
    runs-on: macos-latest
    name: Build assets
    steps:
      - uses: actions/checkout@v4
      - name: Cache pnpm modules
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v3.0.0
        with:
          version: latest
          run_install: true
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 22.x
          cache: "pnpm"
      - name: Build for Mac
        run: pnpm build:mac
      - name: Upload file
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "build/*.dmg"
          tags: false
          draft: false
